### ISSUE TITLE
feed.nickname always empty in specific environments

### ISSUE THREAD

**Issue by JamzumSum** [aioqzone/Qzone2TG#83]
**描述你遇到的问题**

header中的nickname显示为uin

**如何复现此问题**

**复现似乎与地点有关**，固定地点稳定复现，开发环境下无法复现（

**错误日志或截图**
截图会有用，但不一定有什么用。
![f7d804c370ccb281388867c4bf7d5e1](https://user-images.githubusercontent.com/22952836/163713780-e9c16a33-570d-4025-b7d6-c9555ee205e3.jpg)

**必要信息**
 - OS: debian11
 - Qzone3TG 版本或 git 分支：[d19155a7c0883c8c27156b479f6e56b3276bd2ab](https://github.com/aioqzone/Qzone2TG/commit/d19155a7c0883c8c27156b479f6e56b3276bd2ab)
 - 环境：pkg [0.2.10.dev1](https://github.com/aioqzone/Qzone2TG/pkgs/container/qzone3tg/19218202?tag=0.2.10.dev1)

**其他**

问题应该在于 nickname 值始终为""。怀疑 aioqzone-feed 的测试不能在问题环境下通过。

**Comment by TigerCubDen** [comment]
same here

**Comment by JamzumSum** [comment]
https://github.com/aioqzone/aioqzone/issues/34

目前并不知道是什么原因，总之返回的结果里昵称确实是空
不过可以拿用户名代替，最后才是uin
```python
nickname or name or str(uin)
```

**Comment by JamzumSum** [comment]
html里应该可以解析出nickname (aioqzone/aioqzone#35, aioqzone/aioqzone-feed#14)
